[debug]
debug = true
devices = []
function = "debug_fun"
sinks = ["web"]

[debug.source]
event = "debug"
id = "web"

[uart_debug]
debug = true
devices = []
function = "debug_fun"
sinks = [
    "web",
    "uart",
]

[uart_debug.source]
event = "49"
id = "uart"

[uart_black_ring_detect]
debug = true
devices = ["road"]
function = "black_ring_detect"
sinks = [
    "web",
    "uart",
]

[uart_black_ring_detect.source]
event = "4"
id = "uart"

[uart_color_block_detect]
debug = true
devices = ["road"]
function = "color_block_detect"
sinks = [
    "web",
    "uart",
]

[uart_color_block_detect.source]
event = "6"
id = "uart"

[uart_color_detect]
debug = true
devices = ["road"]
function = "color_detect"
sinks = [
    "web",
    "uart",
]

[uart_color_detect.source]
event = "1"
id = "uart"

[uart_concentric_ring_detect]
debug = true
devices = ["road"]
function = "concentric_ring"
sinks = [
    "web",
    "uart",
]

[uart_concentric_ring_detect.source]
event = "3"
id = "uart"

[uart_letter_detect]
debug = true
devices = ["road"]
function = "letter_detect"
sinks = [
    "web",
    "uart",
]

[uart_letter_detect.source]
event = "5"
id = "uart"

[uart_qr_detect]
debug = true
devices = ["task"]
function = "qr_detect"
sinks = [
    "web",
    "uart",
]

[uart_qr_detect.source]
event = "2"
id = "uart"

[uart_sample_black_ring_result]
debug = true
devices = []
function = "sample_black_ring_result"
sinks = ["web", "uart"]

[uart_sample_black_ring_result.source]
event = "20"
id = "uart"

[uart_sample_color_block_result]
debug = true
devices = []
function = "sample_color_block_result"
sinks = ["web", "uart"]

[uart_sample_color_block_result.source]
event = "22"
id = "uart"

[uart_sample_color_result]
debug = true
devices = []
function = "sample_color_result"
sinks = ["web", "uart"]

[uart_sample_color_result.source]
event = "17"
id = "uart"

[uart_sample_concentric_ring_result]
debug = true
devices = []
function = "sample_concentric_ring_result"
sinks = ["web", "uart"]

[uart_sample_concentric_ring_result.source]
event = "19"
id = "uart"

[uart_sample_letter_result]
debug = true
devices = []
function = "sample_letter_result"
sinks = ["web", "uart"]

[uart_sample_letter_result.source]
event = "21"
id = "uart"

[uart_sample_qr_result]
debug = true
devices = []
function = "sample_qr_result"
sinks = ["web", "uart"]

[uart_sample_qr_result.source]
event = "18"
id = "uart"
