[package]
name = "rubo_vision"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
opencv = ["dep:opencv", "dep:quircs", "dep:base64"]
hardware = ["dep:serialport"]

[dependencies]
async-trait = "0.1"
rubo_engine = "0.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }

base64 = { version = "0.22", optional = true }
opencv = { version = "0.75", optional = true }
quircs = { version = "0.10", optional = true }
serialport = { version = "4", optional = true }
