[gpio]
active_low = true
chip = 7
kind = "gpio"
run_pin = 3

[gpio.signals]
color = 4
qr = 5

[uart]
baud = 9600
data_bit = 8
kind = "uart"
parity_bit = false
serial = "/dev/ttyAMA1"
stop_bit = 1

[web]
kind = "web"
