name: rubo_vision
config_path: config
# 可选值：ubuntu、orangepi、raspberrypi
profile: ubuntu
config_format: toml
web:
  enabled: true
  output_image: true
  host: 0.0.0.0
  port: 3888
log:
  enabled: true
  level: info
