[[devices.list]]
device_id = "color_camera"
kind = "Camera"
path = "/dev/video2"

[[devices.list]]
device_id = "qr_camera"
kind = "Camera"
path = "/dev/video2"

[[devices.list]]
device_id = "cross_camera"
kind = "Camera"
path = "/dev/video2"
