[black_ring_detect]
black_threshold = 90
debug_model = false
device_id = "color_camera"
loop_count = 3
max_radius = 180.0
min_circularity = 0.65
min_radius = 20.0
min_score = 50

[black_ring_detect.target_correction]
x = 0
y = 0

[color_detect]
debug_model = false
detect_area_access_rate = 0.8
device_id = "color_camera"
loop_count = 5
radius_ratio = 0.4

[[color_detect.color_ranges]]
hsv = [
    0,
    50,
    160,
    255,
    110,
    255,
]
name = "red"

[[color_detect.color_ranges]]
hsv = [
    100,
    137,
    124,
    255,
    56,
    255,
]
name = "blue"

[[color_detect.color_ranges]]
hsv = [
    50,
    100,
    91,
    255,
    85,
    255,
]
name = "green"

[[color_detect.color_ranges]]
hsv = [
    0,
    179,
    0,
    255,
    0,
    76,
]
name = "black"

[[color_detect.color_ranges]]
hsv = [
    0,
    170,
    0,
    55,
    120,
    255,
]
name = "white"

[cross]
black_threshold = 90
center_tolerance = 14.0
close_kernel_size = 5
debug_model = false
device_id = "cross_camera"
dilate_iterations = 1
dilate_kernel_size = 3
loop_count = 3
max_radius = 600.0
min_arc_points = 24
min_radius = 20.0
min_ring_score = 50

[[cross.colors]]
hsv = [
    0,
    20,
    100,
    255,
    80,
    255,
]
id = 1
min_area = 500.0
min_circularity = 0.6
name = "red"

[[cross.colors]]
hsv = [
    90,
    140,
    80,
    255,
    50,
    255,
]
id = 2
min_area = 500.0
min_circularity = 0.6
name = "blue"

[[cross.colors]]
hsv = [
    35,
    90,
    70,
    255,
    50,
    255,
]
id = 3
min_area = 500.0
min_circularity = 0.6
name = "green"

[[cross.colors]]
hsv = [
    0,
    179,
    0,
    255,
    0,
    70,
]
id = 4
min_area = 500.0
min_circularity = 0.6
name = "black"

[[cross.colors]]
hsv = [
    0,
    179,
    0,
    60,
    230,
    255,
]
id = 5
min_area = 500.0
min_circularity = 0.6
name = "white"

[cross.target_correction]
x = 0
y = 0

[debug_fun]
message = "debug"

[qr_detect]
debug_model = false
device_id = "qr_camera"
loop_count = 30
