[package]
name = "rubo_engine"
version = "0.4.0"
edition.workspace = true
license.workspace = true
description = "A pure Rust core runtime framework for source-device-function-sink pipelines."
readme = "README.md"
documentation = "https://docs.rs/rubo_engine"
keywords = ["runtime", "pipeline", "debugger", "vision"]
categories = ["asynchronous"]

[features]
default = []
hardware = ["dep:serialport"]

[dependencies]
async-trait = "0.1"
axum = "0.8"
config = "0.15"
futures = "0.3"
inventory = "0.3"
owo-colors = "4"
rubo_engine_macros = { version = "0.1.1", path = "../rubo_engine_macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_bw = "2.5"
tokio = { version = "1", features = ["sync", "rt", "macros", "net", "time"] }
toml = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "ansi"] }

[target.'cfg(target_os = "linux")'.dependencies]
serialport = { version = "4.9.0", default-features = false, optional = true }

[dev-dependencies]
tempfile = "3"
